google_project_id       = "neat-bricolage-316221"
google_bucket_name      = "aziza-bucket2"
deployment_environment  = "dev"
deployment_name         = "hello-world"
credentials             = "fuchicorp-service-account.json"